def manual_social_network_leads():
    return [
        {
            "name": "John Doe",
            "title": "VP Preclinical",
            "company": "Novartis",
            "location": "Basel, Switzerland",
            "email": "john.doe@novartis.com",
            "phone": "3245678920",
            "source": "linkedin",
            "tenure_months": 12,
        },
        {
            "name": "Jane Smith",
            "title": "Director of Toxicology",
            "company": "Pfizer",
            "location": "Boston, MA",
            "email": "jane.smith@pfizer.com",
            "phone": "16175550123",
            "source": "linkedin",
            "tenure_months": 24,
        },
        {
            "name": "Robert Johnson",
            "title": "Head of Investigative Toxicology",
            "company": "AstraZeneca",
            "location": "Cambridge, UK",
            "email": "robert.johnson@astrazeneca.com",
            "phone": "442071234567",
            "source": "linkedin",
            "tenure_months": 18,
        },
        {
            "name": "Emily Turner",
            "title": "Principal Scientist, Drug Safety",
            "company": "Biogen",
            "location": "Cambridge, MA",
            "email": "emily.turner@biogen.com",
            "phone": "16175559876",
            "source": "linkedin",
            "tenure_months": 36,
        },
    ]

def manual_publication_leads():
    return [
        {
            "name": "Alice Brown",
            "title": "Head of Safety Assessment",
            "company": "Gilead",
            "location": "San Francisco, CA",
            "email": "alice.brown@gilead.com",
            "phone": "24681012",
            "source": "conference",
            "publication": "AACR 2024 Speaker",
        },
        {
            "name": "Dr.Anna Müller",
            "title": "Principal Investigator",
            "company": "University of Heidelberg",
            "location": "Heidelberg, Germany",
            "email": "anna.mueller@uni-heidelberg.de",
            "phone": "49891234567",
            "source": "pubmed",
            "publication": "3D Hepatic Spheroids for DILI Prediction",
        },
        {
            "name": "Dr.Sofia Alvarez",
            "title": "Associate Professor of Toxicology",
            "company": "University of Barcelona",
            "location": "Barcelona, Spain",
            "email": "sofia.alvarez@ub.edu",
            "phone": "34935556677",
            "source": "pubmed",
            "publication": "Organ-on-Chip Models for Liver Toxicity",
        },
        {
            "name": "Michael Chen",
            "title": "Senior Scientist, Toxicology",
            "company": "Roche",
            "location": "Basel, Switzerland",
            "email": "michael.chen@roche.com",
            "phone": "41615551234",
            "source": "conference",
            "publication": "SOT 2024 Poster Presenter",
        },
    ]
